/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx,html}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#573c00",
        "secondary-container": "#17533a",
        "inverse-surface": "#e1e2e8",
        "tertiary-fixed": "#d4e3ff",
        "on-error": "#690005",
        "surface-container-highest": "#323539",
        tertiary: "#a7caff",
        "surface-bright": "#37393e",
        "secondary-fixed-dim": "#98d3b2",
        "inverse-primary": "#7d5700",
        "on-tertiary-fixed": "#001c39",
        "surface-dim": "#111417",
        "on-primary-fixed-variant": "#5f4100",
        "tertiary-fixed-dim": "#a4c9ff",
        "on-tertiary-container": "#004179",
        "inverse-on-surface": "#2e3135",
        "error-container": "#93000a",
        "primary-fixed-dim": "#f5bd58",
        "surface-container-low": "#191c20",
        primary: "#f7bf59",
        "secondary-fixed": "#b3f0cd",
        "on-tertiary-fixed-variant": "#014883",
        "surface-tint": "#f5bd58",
        surface: "#111417",
        "on-surface-variant": "#d3c4b1",
        "primary-container": "#d9a441",
        "surface-variant": "#323539",
        background: "#111417",
        "on-secondary-fixed-variant": "#145037",
        "outline-variant": "#4f4536",
        "on-primary": "#422c00",
        outline: "#9c8f7d",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#8ac5a5",
        secondary: "#98d3b2",
        "on-surface": "#e1e2e8",
        "on-background": "#e1e2e8",
        "surface-container-high": "#272a2e",
        "primary-fixed": "#ffdeaa",
        "on-secondary-fixed": "#002113",
        error: "#ffb4ab",
        "on-primary-fixed": "#271900",
        "tertiary-container": "#7faff1",
        "surface-container": "#1d2024",
        "on-secondary": "#003824",
        "surface-container-lowest": "#0c0e12",
        "on-tertiary": "#00315d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "margin-mobile": "16px",
        "container-max": "1120px",
        "section-gap": "80px",
        "margin-desktop": "48px",
        gutter: "24px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ['"Source Serif 4"', "serif"],
        "mono-ui": ["Inter", "sans-serif"],
        "display-lg-mobile": ['"Source Serif 4"', "serif"],
        "headline-md": ['"Source Serif 4"', "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        serif: ['"Source Serif 4"', "serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": [
          "13px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "mono-ui": [
          "14px",
          { lineHeight: "20px", fontWeight: "400" },
        ],
        "display-lg-mobile": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", fontWeight: "500" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "30.6px", fontWeight: "400" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "27.2px", fontWeight: "400" },
        ],
      },
      boxShadow: {
        "glow-primary":
          "0 0 15px rgba(217,164,65,0.2)",
      },
      keyframes: {
        "pulse-opacity": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "status-pulse":
          "pulse-opacity 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};
